### ISSUE TITLE
firebaseとの連携について

### ISSUE THREAD

**Issue by kuroponzu** [kuroponzu/Flutter_App_test#1]
flutterをfirebaseに連携させて、データのやり取りをする場合、cloud firestoreを使うみたい
(というか、その記事しか出てこない)
問題は、cloud firestoreがベータ版のため、記事も少なく、使い方がよく分からん。
なので、[ここ](https://github.com/flutter/plugins/tree/master/packages/cloud_firestore)見て頑張るしか

てか、素直に[firebase](https://pub.dartlang.org/packages/firebase_database)使えばいいのでは
続きはまた明日。
頑張ろう

**Comment by kuroponzu** [comment]
メモ
https://qiita.com/clarinet758/items/a05d855955aff27314b9
https://dev.classmethod.jp/smartphone/flutter_firebase-realtime-database1/

**Comment by wamisnet** [comment]
closeかな？？
